/** Auto-generated by scripts/import-adscars.mjs — do not edit by hand. */

export const MARQUES = [
  "Mercedes-Benz",
  "Ferrari",
  "Rolls-Royce",
  "Lamborghini",
  "Corvette",
  "Porsche",
  "Bentley",
  "Aston Martin",
  "McLaren",
  "Land Rover",
  "AM General",
  "Aprilia",
  "Audi",
  "BMW",
  "Cadillac",
  "Chevrolet",
  "Datsun",
  "Dodge",
  "Ford",
  "Genesis",
  "Honda",
  "Ineos",
  "Jeep",
  "Kia",
  "Lexus",
  "Maserati",
  "Morgan Aero",
  "Nissan",
  "Pontiac",
  "Thor",
  "Toyota",
] as const;

export type Marque = (typeof MARQUES)[number] | string;
export type BrandSlug = string;

export interface Brand {
  name: string;
  slug: string;
  href: `/inventory/${string}`;
}

export const BRANDS: Brand[] = [
  { name: "Mercedes-Benz", slug: "mercedes-benz", href: "/inventory/mercedes-benz" },
  { name: "Ferrari", slug: "ferrari", href: "/inventory/ferrari" },
  { name: "Rolls-Royce", slug: "rolls-royce", href: "/inventory/rolls-royce" },
  { name: "Lamborghini", slug: "lamborghini", href: "/inventory/lamborghini" },
  { name: "Corvette", slug: "corvette", href: "/inventory/corvette" },
  { name: "Porsche", slug: "porsche", href: "/inventory/porsche" },
  { name: "Bentley", slug: "bentley", href: "/inventory/bentley" },
  { name: "Aston Martin", slug: "aston-martin", href: "/inventory/aston-martin" },
  { name: "McLaren", slug: "mclaren", href: "/inventory/mclaren" },
  { name: "Land Rover", slug: "land-rover", href: "/inventory/land-rover" },
  { name: "AM General", slug: "am-general", href: "/inventory/am-general" },
  { name: "Aprilia", slug: "aprilia", href: "/inventory/aprilia" },
  { name: "Audi", slug: "audi", href: "/inventory/audi" },
  { name: "BMW", slug: "bmw", href: "/inventory/bmw" },
  { name: "Cadillac", slug: "cadillac", href: "/inventory/cadillac" },
  { name: "Chevrolet", slug: "chevrolet", href: "/inventory/chevrolet" },
  { name: "Datsun", slug: "datsun", href: "/inventory/datsun" },
  { name: "Dodge", slug: "dodge", href: "/inventory/dodge" },
  { name: "Ford", slug: "ford", href: "/inventory/ford" },
  { name: "Genesis", slug: "genesis", href: "/inventory/genesis" },
  { name: "Honda", slug: "honda", href: "/inventory/honda" },
  { name: "Ineos", slug: "ineos", href: "/inventory/ineos" },
  { name: "Jeep", slug: "jeep", href: "/inventory/jeep" },
  { name: "Kia", slug: "kia", href: "/inventory/kia" },
  { name: "Lexus", slug: "lexus", href: "/inventory/lexus" },
  { name: "Maserati", slug: "maserati", href: "/inventory/maserati" },
  { name: "Morgan Aero", slug: "morgan-aero", href: "/inventory/morgan-aero" },
  { name: "Nissan", slug: "nissan", href: "/inventory/nissan" },
  { name: "Pontiac", slug: "pontiac", href: "/inventory/pontiac" },
  { name: "Thor", slug: "thor", href: "/inventory/thor" },
  { name: "Toyota", slug: "toyota", href: "/inventory/toyota" },
];

export const BRAND_BY_SLUG: Record<string, Brand> = Object.fromEntries(
  BRANDS.map((brand) => [brand.slug, brand])
);

export const BRAND_BY_NAME: Record<string, Brand> = Object.fromEntries(
  BRANDS.map((brand) => [brand.name, brand])
);

export function isBrandSlug(value: string): boolean {
  return value in BRAND_BY_SLUG;
}

export function getBrandBySlug(slug: string): Brand | null {
  return BRAND_BY_SLUG[slug] ?? null;
}

export function marqueToSlug(marque: string): string {
  return BRAND_BY_NAME[marque]?.slug ?? marque.toLowerCase().replace(/[^a-z0-9]+/g, "-");
}

export function brandHref(marque: string): Brand["href"] {
  const brand = BRAND_BY_NAME[marque];
  return (brand?.href ?? `/inventory/${marqueToSlug(marque)}`) as Brand["href"];
}

/** Tailwind gradient fragments for card / badge accents */
export const MARQUE_ACCENTS: Record<string, string> = {
  "Mercedes-Benz": "from-zinc-300/35 via-zinc-500/15 to-transparent",
  "Ferrari": "from-red-600/40 via-red-900/20 to-transparent",
  "Rolls-Royce": "from-stone-200/30 via-amber-200/10 to-transparent",
  "Lamborghini": "from-yellow-400/35 via-amber-700/20 to-transparent",
  "Corvette": "from-red-500/35 via-zinc-800/20 to-transparent",
  "Porsche": "from-amber-500/30 via-stone-600/20 to-transparent",
  "Bentley": "from-emerald-700/35 via-green-900/20 to-transparent",
  "Aston Martin": "from-green-600/35 via-emerald-900/20 to-transparent",
  "McLaren": "from-orange-500/35 via-amber-800/20 to-transparent",
  "Land Rover": "from-green-500/30 via-stone-700/20 to-transparent",
  "AM General": "from-gold-light/25 via-zinc-700/15 to-transparent",
  "Aprilia": "from-gold-light/25 via-zinc-700/15 to-transparent",
  "Audi": "from-slate-300/30 via-zinc-600/20 to-transparent",
  "BMW": "from-blue-500/30 via-zinc-700/20 to-transparent",
  "Cadillac": "from-zinc-200/30 via-zinc-600/20 to-transparent",
  "Chevrolet": "from-yellow-500/30 via-zinc-700/20 to-transparent",
  "Datsun": "from-gold-light/25 via-zinc-700/15 to-transparent",
  "Dodge": "from-red-700/30 via-zinc-800/20 to-transparent",
  "Ford": "from-blue-600/30 via-zinc-800/20 to-transparent",
  "Genesis": "from-zinc-400/30 via-zinc-700/20 to-transparent",
  "Honda": "from-gold-light/25 via-zinc-700/15 to-transparent",
  "Ineos": "from-gold-light/25 via-zinc-700/15 to-transparent",
  "Jeep": "from-green-700/30 via-stone-800/20 to-transparent",
  "Kia": "from-gold-light/25 via-zinc-700/15 to-transparent",
  "Lexus": "from-stone-300/30 via-zinc-600/20 to-transparent",
  "Maserati": "from-blue-400/30 via-blue-900/20 to-transparent",
  "Morgan Aero": "from-gold-light/25 via-zinc-700/15 to-transparent",
  "Nissan": "from-gold-light/25 via-zinc-700/15 to-transparent",
  "Pontiac": "from-gold-light/25 via-zinc-700/15 to-transparent",
  "Thor": "from-gold-light/25 via-zinc-700/15 to-transparent",
  "Toyota": "from-gold-light/25 via-zinc-700/15 to-transparent",
};

export const DEFAULT_MARQUE_ACCENT = "from-gold-light/25 via-zinc-700/15 to-transparent";
